export const ExampleData = [
    {
        id:"01",
        firstname:"Qavi",
        lastname:"Ashraf",
        email:"qaviashraf@gmail.com",
        password:"1234",
        orders:[
            {
                order_id:"0001",
                customer_name:"Abdul Basit",
                mobile_number:"0313030402",
                email:"basit@gmail.com",
                address:"lyari karachi",
                category:"Laptop",
                product:"Dell Laptop",
                status:"Pending",
                deliveryDate:"2023/08/30",
            },
            {
                order_id:"0001",
                customer_name:"Abdul Basit",
                mobile_number:"0313030402",
                email:"basit@gmail.com",
                address:"lyari karachi",
                category:"Mobile",
                product:"Samsung Note 20",
                status:"Delivered",
                deliveryDate:"2023/07/23",   
            },
            {
                order_id:"0001",
                customer_name:"Abdul Basit",
                mobile_number:"0313030402",
                email:"basit@gmail.com",
                address:"lyari karachi",
                category:"Airbuds",
                product:"M-10",
                status:"Delivered",
                deliveryDate:"2023/07/23",   
            },
            {
                order_id:"0001",
                customer_name:"Abdul Basit",
                mobile_number:"0313030402",
                email:"basit@gmail.com",
                address:"lyari karachi",
                category:"Mobile",
                product:"Realme 25Y",
                status:"Delivered",
                deliveryDate:"2023/02/23",   
            },
            {
                order_id:"0001",
                customer_name:"Abdul Basit",
                mobile_number:"0313030402",
                email:"basit@gmail.com",
                address:"lyari karachi",
                category:"Mobile",
                product:"IPhone 14",
                status:"Delivered",
                deliveryDate:"2023/03/23",   
            }
        ]
    },
    {
        id:"02",
        firstname:"Abdul",
        lastname:"Basit",
        email:"basit@gmail.com",
        password:"9876",
        orders:[
            {
                order_id:"0001",
                customer_name:"Qavi",
                mobile_number:"2819489412",
                email:"qavi@gmail.com",
                address:"Nagin",
                category:"Bike",
                product:"Super Power Bike",
                status:"Delivered",
                deliveryDate:"2023/01/23",
            },
            {
                order_id:"0002",
                customer_name:"Qavi",
                mobile_number:"2819489412",
                email:"qavi@gmail.com",
                address:"Nagin",
                category:"Car",
                product:"Sportage",
                status:"Pending",
                deliveryDate:"2023/01/23",
            },
            {
                order_id:"0003",
                customer_name:"Qavi",
                mobile_number:"2819489412",
                email:"qavi@gmail.com",
                address:"Nagin",
                category:"Bike",
                product:"Super Power Bike",
                status:"Pending",
                deliveryDate:"2023/05/23",
            },
        ]
    },
    {
        id:"03",
        firstname:"Usman",
        lastname:"Khan",
        email:"usman@gmail.com",
        password:"123",
        orders:[
            {
                order_id:"0001",
                customer_name:"Usman",
                mobile_number:"2819489412",
                email:"Usman@gmail.com",
                address:"Orangi",
                category:"Car",
                product:"City",
                status:"Delivered",
                deliveryDate:"2023/03/23",
            },
            {
                order_id:"0002",
                customer_name:"Usman",
                mobile_number:"2819489412",
                email:"Usman@gmail.com",
                address:"Orangi",
                category:"Bike",
                product:"Super Power Bike",
                status:"Pending",
                deliveryDate:"2023/03/23",
            },
            {
                order_id:"0003",
                customer_name:"Usman",
                mobile_number:"2819489412",
                email:"Usman@gmail.com",
                address:"Orangi",
                category:"Car",
                product:"Civic",
                status:"Pending",
                deliveryDate:"2023/01/23",
            },
            {
                order_id:"0004",
                customer_name:"Usman",
                mobile_number:"2819489412",
                email:"Usman@gmail.com",
                address:"Orangi",
                category:"Bike",
                product:"Super Power Bike",
                status:"Delivered",
                deliveryDate:"2023/09/23",
            },
            {
                order_id:"0005",
                customer_name:"Usman",
                mobile_number:"2819489412",
                email:"Usman@gmail.com",
                address:"Orangi",
                category:"Bike",
                product:"Super Power Bike",
                status:"Delivered",
                deliveryDate:"2023/03/23",
            },
        ]
    }
]