export const ExampleData = [
    {
        id:"",
        firstname:"",
        lastname:"",
        email:"",
        password:"",
        orders:[
            {
                order_id:"",
                customer_name:"",
                mobile_number:"",
                email:"",
                address:"",
                product:"",
                status:"",
                deliveryDate:"",
            },
        ]
    },
    {
        id:"",
        firstname:"",
        lastname:"",
        email:"",
        password:"",
        orders:[
            {
                order_id:"",
                customer_name:"",
                mobile_number:"",
                email:"",
                address:"",
                product:"",
                status:"",
                deliveryDate:"",
            },
        ]
    }
]